---
title: "fireSense_SizeFit"
author: "Jean Marchal"
date: "August 2016"
output:
  html_document: default
  pdf_document: default
---

# Overview
Fit statistical models of the fire size distribution. A tapered Pareto distribution
is assumed. This distribution has three parameters: *a*, $\beta$ and $\theta$; *a* is
the lower truncation point and is assumed to be known *a* priori, $\beta$ controls the
rate of frequency decrease as fire size increases, finally $\theta$ governs the location of
the exponential taper. This module can be used to relate $\beta$ and $\theta$ with
environmental controls of the fire size distribution.


# Usage

```{r module_usage, eval = FALSE}
library(SpaDES)
library(DEoptimR)
library(magrittr)
library(numDeriv)
library(PtProcess)

set.seed(1)

df <- data.frame(
  weather = rnorm(1000, 150, 30),
  fireFrequency = rpois(1000, .5)
)

#outputDir <- file.path(tempdir(), "outputs")
times <- list(start = 1, end = 1)
parameters <- list(
  fireSense_FrequencyFit = list(
    formula = formula(fireFrequency ~ weather),
    data = "df", ## TODO: where the data lives
    trace = 5 # Print progress every trace iteration
  )
)

modules <- list("fireSense_SizeFit")
objects <- "df"
paths <- list(
  # cachePath = file.path(outputDir, "cache"),
  modulePath = file.path("~/Documents/GitHub/McIntire-lab/modulesPrivate/") ## TODO: change this to tempdir()
  # inputPath = inputDir,
  # outputPath = outputDir
)

## TODO: - provide example for partial matching for list(beta =, theta = )
 
mySim <- simInit(times = times, params = parameters, modules = modules, objects = objects, paths = paths)

spades(mySim)
```

# Events

Describe what happens for each event type.

## Plotting

Write what is plotted.

## Saving

Write what is saved.

# Data dependencies

## Input data

How to obtain input data, and a description of the data required by the module.
If `sourceURL` is specified, `downloadData("fireSense_Size", "path/to/modules/dir")` may be sufficient.

## Output data

Description of the module outputs.

# Links to other modules

Describe any anticipated linkages to other modules.

